bayesian-optimization/BayesianOptimization

- bayes_opt/bayesian_optimization.py
According to Snoek et al. the Matern 5/2 kernel performed the best in empirical
tests. Also, this commit changed the default acquisition function to 'ei' to
match the docstring.
> Changed default correlation model to the Matern 5/2 kernel

- bayes_opt/bayesian_optimization.py
Added method that allows to add points for which target variable is known from pandas dataframe with signature:
`(target, {list of columns matching self.keys})`
ex:
```     
target        alpha      colsample_bytree        gamma
-1166.19102       7.0034                0.6849       8.3673
-1142.71370       6.6186                0.7314       3.5455
-1138.68293       6.0798                0.9540       2.3281
-1146.65974       2.4566                0.9290       0.3456
-1160.32854       1.9821                0.5298       8.7863
```
> Added initialization from pandas DataFrame

- examples/xgboost_example.py
Added example for xgboost with native cross-validation support. Works on the data from https://www.kaggle.com/c/allstate-claims-severity/data
> Added xgboost example

- bayes_opt/bayesian_optimization.py
- examples/xgb_example.py
Added method that saves known datapoints as a csv file.
ex:
```
target        alpha      colsample_bytree        gamma
-1166.19102       7.0034                0.6849       8.3673
-1142.71370       6.6186                0.7314       3.5455
-1138.68293       6.0798                0.9540       2.3281
-1146.65974       2.4566                0.9290       0.3456
-1160.32854       1.9821                0.5298       8.7863
```
Format is consistent with `initialize_df` method and as a result allows to address https://github.com/fmfn/BayesianOptimization/issues/28
> Added method points_to_csv that saves known data points to csv file

- bayes_opt/bayesian_optimization.py
- Fixes #46 
- Adds example for initialize function
> Fixes bug in initialize

- bayes_opt/bayesian_optimization.py
I often plot/monitor the optimisation each iteration in case I want to stop early or change some parameters. I do this by adding monitoring code to the target function.
Currently, the x and y values checked during `explore` and `init` are not accessible (stored on the `bo` object) until after both steps are complete, which can take a long time for expensive functions. 
This PR adds updates `self.X` and `self.Y` each iteration of the explore/init step. Most of the logic is converting `append` and `+=` to numpy equivalents. Adds a bit of complexity but doesn't change any other part of the API.
You could go all out and also update `bo.go.fit()` and `bo.res` each iteration, and add callback parameter 
to be called after each iteration to avoid hacking the target function like xgboost and some …
> Update X and Y during init

- .travis.yml
- bayes_opt/bayesian_optimization.py
- bayes_opt/helpers.py
- bayes_opt/target_space.py
- pytest.ini
- tests/test_bayesian_optimization.py
- tests/test_helper_functions.py
- tests/test_target_space.py
- tests/tests_helper_functions.py
This PR address an issue I've been experiencing in interactive use. I want to run the maximization function and then try custom values based in its result. However, the only way to do that is to "initialize", and doing that blows away all previous values of `self.X` and `self.Y`. 
To this end I made a function `explore_eager` (name pending), which works like `explore`, but immediately evaluates those values and adds them to your current explored data. It does this in such a way that if self.maximize is called again it uses the new custom points when it fits its GMM. 
Now, to make this change I had to do some non-trivial code refactoring. I saw a few issues in the code base that I felt I should address while I was in there. The main problem was the use of np.vstack and np.append after …
> explore_eager and new data structure for efficient appends

- bayes_opt/bayesian_optimization.py
The current `header` argument in the `np.savetxt` call inside of the `points_to_csv` method is not compatible with the format expected from the `initialize_df` method.
A call to `initialize_df` when the argument is a pandas DataFrame constructed by reading the output of `points_to_csv` with `pandas.read_csv` will fail because of a wrong format of the header.
In particular, the issues here are the following:
1. the header of the csv file is generated with a leading pound character ('#') that comes from the default `comments='#'` of `np.savetxt`
2. the column names are prefixed with an unnecessary space in by `', '.join(self.space.keys + ['target'])` inside of `points_to_csv`.
This pull request fixes the above two issues. I tested these changes on a notebook that I am happy to share upon …
> Fix csv issue in the points_to_csv method

- bayes_opt/__init__.py
- bayes_opt/bayesian_optimization.py
- bayes_opt/event.py
- bayes_opt/observer.py
- bayes_opt/target_space.py
- bayes_opt/util.py
- tests/test_bayesian_optimization.py
- tests/test_helper_functions.py
This commit refactors heavily how loggin is done in the package. It
removes the old style of loggin and does everything now using observers.
By default the user has access to two useful observers, json and
printer, and if the users doesn't want to deal with that the verbose
parameter takes care of the basics.
> Default and ready to use observers

- bayes_opt/target_space.py
Bounds matrix was being created without sorting for keys first. This
made things quite inconsistent. This commit fixes it.
> Fix bounds-key ordering inconsistency

- examples/async_optimization.py
The async example was calling `register` with a parameter `x`, this is
the old style. This commit changes it to `params` fixing a bug.
> Fix parameter name in async example

- setup.py
This will stop the [PyPI page](https://pypi.org/project/bayesian-optimization/) looking bare with "The author of this package has not provided a project description."
> Add long_description to README

- README.md
- examples/advanced-tour.ipynb
This commit improves the Suggest-Evaluate-Register example by passing
no blackbox function to the optimizer making it clear it is not needed
in this scenario.
> Improve the Suggest-Evaluate-Register example

- bayes_opt/bayesian_optimization.py
- bayes_opt/util.py
> add kappa decay

- README.md
- bayes_opt/logger.py
Quick fix so that when loading a log file, the information it is not lost. Having an option to fix #159 easily. For backwards compatibility, reset is set to True.
> Added option to keep using an older log (Save -> Load -> Save)

- bayes_opt/bayesian_optimization.py
- tests/test_bayesian_optimization.py
A quick check following the 'don't ask for permission ask for forgiveness' motto to make sure that the bounds_transformer used can be called otherwise a clear exception message is shown.
> Check bounds_transformation is correct type

- .gitignore
Since it is best practice to create virtual environments for each python project. I've thought that it would be nice to have it on gitignore.
> Add virtual environments folders to gitignore

- bayes_opt/util.py
Simple change, just uses `np.squeeze` to ensure the result gets handled as a float.
> Fixes the error caused by scipy 1.8 minimize results changing.

- bayes_opt/bayesian_optimization.py
There is a small typo in bayes_opt/bayesian_optimization.py.
Should read `provided` rather than `provieded`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, provieded -> provided

- examples/advanced-tour.ipynb
Hi, 
I just spotted simple typos while I ran advanced-tour.ipynb.
definying->defining, problemn->problem
> 2 typo fixes in advanced-tour.ipynb

- bayes_opt/logger.py
> Fix JSONLogger with constraints

- bayes_opt/bayesian_optimization.py
> change Deprecation warning to Error

- bayes_opt/util.py
This makes the acqusition function equivalent to the unconstrained case if the GP is certain that the constraint is fulfilled.
NB: Should we add a note somewhere that constrained optimization is best used with the EI acquisition function?
> Update acquisition function scaling for constrained optimization

- bayes_opt/target_space.py
- bayes_opt/util.py
- tests/test_constraint.py
Fixes #412 
Previously the warmup phase would use the acquisition function directly without considering the p_constraint. This could lead to inflated values of the acquisition function in unfeasible spaces.
> Fix warmup phase not considering constraints

- bayes_opt/target_space.py
- tests/test_target_space.py
This commit fixes the bug in TargetSpace.max() when the space is constrained which lead to sometimes returning the parameters from a unfeasible point when its target value coincided with the best feasible point.
Closes #428
> Fixes issue-428: TargetSpace.max() bug in constrained space

- bayes_opt/domain_reduction.py
- bayes_opt/target_space.py
- tests/test_logs_bounds.log
- tests/test_seq_domain_red.py
- tests/test_target_space.py
- tests/test_util.py
Previously, when the upper limit of  new_bounds < lower limit of global_bounds, the new_bounds could bypass the global_bounds.  The proposed changes requires the little change to the existing code, but could cause one of the entries in new_bounds to stagnate at the global_bounds if the new_bounds entry is always outside of the global_bounds.
> bounds_transformer could bypass global_bounds due to the test logic within _trim function in domain_reduction.py

- bayes_opt/logger.py
- bayes_opt/target_space.py
Addresses issue #488 by resetting colour code after each value in `logger::_step`.
Also resets the use of red in target_space when warning about duplicate points being added.
> Update logger.py to reset color escape sequence in between values

- .github/workflows/run_tests.yml
- pyproject.toml
https://github.com/bayesian-optimization/BayesianOptimization/issues/490#issue-2394383006
> chore: Support numpy v2

- bayes_opt/acquisition.py
- bayes_opt/util.py
- docsrc/code_docs.rst
- docsrc/examples.rst
I knew I had forgotten something in the original PR!
- adds the `acquisition.py` module to the code docs
- adds the `acquisition_functions.ipynb` notebook to the docs
- moves exceptions from `acquisition.py` to `util.py` (where `NotUniqueError` was already defined)
> docs: Add acquisition functions

- bayes_opt/target_space.py
The example sampling results in the comments of the `random_sample()` function in the `target_space.py` file may have been written backwards.
```python
Examples
--------
>>> target_func = lambda p1, p2: p1 + p2
>>> pbounds = {'p1': (0, 1), 'p2': (1, 100)}
>>> space = TargetSpace(target_func, pbounds, random_state=0)
>>> space.random_sample()
array([[ 55.33253689,   0.54488318]])
```
It should be amended to:
```python
Examples
--------
>>> target_func = lambda p1, p2: p1 + p2
>>> pbounds = {'p1': (0, 1), 'p2': (1, 100)}
>>> space = TargetSpace(target_func, pbounds, random_state=0)
>>> space.random_sample()
array([[0.54488318 ,   55.33253689]])
```
The example may mislead users.
> fix docs for `TargetSpace.random_sample`

- bayes_opt/logger.py
Before I applied #497  it worked like this
https://github.com/bayesian-optimization/BayesianOptimization/blob/bc9af23981cb22b98344424b5c2544b741b74938/bayes_opt/logger.py#L167
but after,
https://github.com/bayesian-optimization/BayesianOptimization/blob/16c00f3b7867d7cf43047b2c80d4b6e54156b5e8/bayes_opt/logger.py#L164
I expect it to work the same as before.
> fix: Incorrectly modified `ScreenLogger`

- .github/workflows/build_docs.yml
this allows the actions permissions to not include `write` by default
> `contents: write` permission for versions workflow

- bayes_opt/acquisition.py
- bayes_opt/bayesian_optimization.py
- bayes_opt/constraint.py
- bayes_opt/domain_reduction.py
- bayes_opt/logger.py
- bayes_opt/observer.py
- bayes_opt/target_space.py
- bayes_opt/util.py
- docsrc/conf.py
- pyproject.toml
- tests/test_constraint.py
- tests/test_target_space.py
related: #493 
I didn't use the generic and added type hints using primitive types in most cases.
Therefore, I ignored some types with `Any`.
I also ignored some errors from the static type checker.
Hopefully, this will provide a better IDE experience than before.
> Fix add typehint without generic

- pyproject.toml
closes: #493 
PEP561: https://peps.python.org/pep-0561/
Based on the previous discussion, type hinting using `TypeVar` was ruled out as it would be a barrier to entry for casual users. Instead, #507  was merged in.
In my opinion, this library fully meets the needs of the existing contributors and users, 
so it makes sense to add `py.typed` to let users know that this library provides sufficient type hints.
> Apply PEP561

- .pre-commit-config.yaml
- pyproject.toml
- tests/test_acquisition.py
- tests/test_constraint.py
Bump the version of `ruff` from `0.5.2` to `0.6.6`.
And fix the `PT001` error.
> The default behavior of `PT001` has changed from `0.6.0`.
> see more: https://github.com/astral-sh/ruff/pull/12106
> chore: bump ruff

- tests/test_acquisition.py
Importing errors from `acquisition` does not currently cause any problems at runtime.
However, it is done implicitly and may cause problems in the future.
Therefore, it is safer to explicitly import from `exception`.
> fix: replace acquisition with exception when import error

- bayes_opt/acquisition.py
Given the use case below, it seems that `base_acquisitions` in `GPHedge` can have multiple types of `AcquisitionFunction`.
https://github.com/bayesian-optimization/BayesianOptimization/blob/10ef3be32bd2dd2e9739f430db98a71ae440c4d8/tests/test_acquisition.py#L276
However, the type args in `list` are fixed, so they do not allow such a situation. 
Therefore, we need to change to `Sequence`, which allows args with `covariant=True`.
I was going to ignore it because it's related to generics,
but it seemed necessary for the use case you're considering, so I fixed it.
> [!NOTE]  
> This is not a complete description.
> But I think it will help you understand why the error is occurring.
- `list[T: AcquisitionFunction]`: All elements in `list` are `T`.
> correct case: `[UpperConfidenceBound]` does …
> fix(GPHedge): replace list with sequence

- bayes_opt/domain_reduction.py
`minimum_window` should be typechecked using `Mapping`, not `dict`.
Also, `minimum_window_value` should be typechecked using `Sequence`, not `list`.
And I found it while checking it, is it possible for `minimum_window` to be `None`?
The annotation and docstring on `minimum_window` don't match.
Also, there doesn't seem to be any handling for the case where `minimum_window` is `None` in `SequentialDomainReductionTransformer._trim()`.
https://github.com/bayesian-optimization/BayesianOptimization/blob/10ef3be32bd2dd2e9739f430db98a71ae440c4d8/bayes_opt/domain_reduction.py#L211-L212
In my opinion, `typing.Optional` was used to mean `minimum_window` has a default value. https://github.com/bayesian-optimization/BayesianOptimization/blob/a6697aabf590c9c6f3000b55c5195401b37cff98/bayes_opt/domain_red …
> Fix min window type check

- README.md
Unfortunately a vulnerability patch broke the dynamic badge, see badges/shields#10553. This changes the badge to static -- we can in the future maybe figure out how to make it dynamic again.
> Fix docs badge

- bayes_opt/bayesian_optimization.py
- bayes_opt/target_space.py
Move the warning from the target space to the optimizer
- Show the warning for both `register` and `probe`
- When priming the queue, now adds `dict`-valued samples instead of arrays to avoid triggering the warning.
Unfortunately, this will necessitate a new release.
c.f. _post by @anates in https://github.com/bayesian-optimization/BayesianOptimization/issues/530#issuecomment-2550715125_
> Fix array registration warning

- .github/workflows/build_docs.yml
- .github/workflows/format_and_lint.yml
- .github/workflows/run_tests.yml
- pyproject.toml
What's different in poetry2.0: [Announcing Poetry 2.0.0](https://python-poetry.org/blog/announcing-poetry-2.0.0/)
Since poetry2.0 now supports pep621, I was able to modify pyproject.toml to conform to the standard spec.
(I kept the modifications to a minimum).
(Since [install-poetry](https://github.com/snok/install-poetry) doesn't support poetry2.0, I've changed how to install poetry from github action. https://github.com/snok/install-poetry/issues/164)
However, it does not yet support pep735 (dependency groups), so the proprietary specification `tool.poetry.group` is retained.
However, this too will be fixed in the future. https://github.com/python-poetry/poetry/issues/9751
If we use poetry in the future, it seems like a good idea to upgrade poetry to 2.0 if possible, as all improvements …
> upgrade poetry2.0 & apply pep621

- .github/workflows/run_tests.yml
technically a draft PR, but I need the CI to run to see if it works now.
> Fix coverage

- bayes_opt/parameter.py
> Fix printing for some parameters

- .github/workflows/build_docs.yml
Ubuntu 20.04 LTS runner was removed on 2025-04-15. Switching to `latest`, which mirrors the setup of the other workflows.
> Update Ubuntu runner for build_docs.yml

- bayes_opt/acquisition.py
I noticed this while porting the project to another environment
> Stop duplicating ensure_rng in AcquisitionFunction class

- bayes_opt/target_space.py
Cleans up another little weird bit of code I noticed
> Fix weird formatting

- .github/workflows/build_docs.yml
- bayes_opt/acquisition.py
- pyproject.toml
- tests/test_constraint.py
This fixes a bug introduced in v2.0.0 (by me) which would cause a not-optimal point to be selected by the l-bfgs-b step of the acquisition function maximization.
> bugfix: l-bfgs-b acquisition maximization

- bayes_opt/acquisition.py
- bayes_opt/bayesian_optimization.py
- tests/test_acquisition.py
- tests/test_bayesian_optimization.py
v3.x.x. version of #563
It looks like this bug also caused a test to pass which should've failed. I also fixed that in this PR.
> bugfix: l-bfgs-b acquisition maximization (v3.x.x)
